### ISSUE TITLE
Figure out how to implement non-blocking UART write

### ISSUE THREAD

**Issue by ivmarkov** [esp-rs/esp-idf-hal#11]
As per a comment from @MabezDev:
> Could non blocking be implemented using uart_wait_tx_done with a low (or 0) timeout.

**Comment by andresv** [comment]
FYI: this PR should add support for non-blocking writes https://github.com/esp-rs/esp-idf-hal/pull/84 however it is not entirely tested yet.

**Comment by ivmarkov** [comment]
Related: https://github.com/esp-rs/esp-idf-hal/tree/async-uart

**Comment by ivmarkov** [comment]
Merged.
