### ISSUE TITLE
add component to idf

### ISSUE THREAD

**Issue by farbodpm** [esp-rs/esp-idf-hal#116]
hello, 
I need to add some components to "sys-idf". how can I do it? 

I tested this way.
1. clone sys-idf-hal
2. add esp-littlfs to components
3. add esp-littlefs to binding.h
4. build it.

but I think this is not right.

**Comment by MabezDev** [comment]
Duplicate, see https://github.com/esp-rs/esp-idf-sys/issues/116#issuecomment-1214329068
