### ISSUE TITLE
SPI transaction invert Chip Select

### ISSUE THREAD

**Issue by reinismu** [esp-rs/esp-idf-hal#119]
I'm not sure if this is the place to open this issue, but maybe I have missed a config option to do it.

I'm currently writing a driver for AS3910 RFID reader/writer. To select it you need to set CS to high.
![image](https://user-images.githubusercontent.com/35471680/185608830-88cbfa4f-a64f-412e-a296-6446b8490007.png)

By default HAL is written to set it low on select. Is there some config that could address this?

**Comment by reinismu** [comment]
Went with Embedded hal v0.2.7 and did Chip Select manually. From what I have read I wont be able to push SPI speed to max now, but works

**Comment by Dominaezzz** [comment]
You could make a PR to expose the config option.

**Comment by reinismu** [comment]
I can't find the issue, but it was talked about it somewhere here https://github.com/espressif/esp-idf/issues/
Another thing is that you can get high-frequency SPI to max 3 slave devices. So from what I understand you would still need to make your own custom solution if you need 3+ salve devices

**Comment by ivmarkov** [comment]
This is fixed in the latest SPI driver.
