### ISSUE TITLE
Create an important task

### ISSUE THREAD

**Issue by usbalbin** [esp-rs/esp-idf-hal#120]
Sorry if this is the wrong repo to ask this.

I have an application where I need to run a tight regulation loop preferably without interruption on a two core ESP32 or possibly ESP32-S3 device. I also have other less latency sensitive tasks that will run in the background (web server etc). What would be the best solution?

* Would it make sense to run the regulation loop in its own task pinned to core1? ([`xTaskCreatePinnedToCore`](https://docs.espressif.com/projects/esp-idf/en/v4.4.2/esp32/api-reference/system/freertos.html#_CPPv423xTaskCreatePinnedToCore14TaskFunction_tPCKcK8uint32_tPCv11UBaseType_tPC12TaskHandle_tK10BaseType_t)?)
* Can/Should I disable [Tick Interrupts ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/freertos-smp.html#tick-interrupts) on core1? I still want the webbserver and Wifi to function ok. However that is handled by core0 right?

How do I do this? Is all of this possible today from rust? If not, to what crate should a PR for this be committed?

Am I approaching this wrong?

**Comment by ivmarkov** [comment]
I think the best place for such questions would be the Matrix chat, rather than opening issues in the e-HAL crate. Please join us in the chat room!
