### ISSUE TITLE
v0.38.1 released on crates.io but not tagged

### ISSUE THREAD

**Issue by maximeborges** [esp-rs/esp-idf-hal#126]
I added a comment on the last release commit but I'm not really sure of the visibility of it to the author or maintainers, so pinging @ivmarkov here just in case.

This commit changes the version of the package and seems to have been published to crates.io, but the git tag isn't present/hasn't been pushed here.

**Comment by ivmarkov** [comment]
Yes, the CI pipeline was unfortunately half-broken at the time, and it managed to release, while the tagging (and docu failed). I'll just re-run it and release 0.38.2 shortly.

**Comment by N3xed** [comment]
I tagged `v.38.1` manually in the meantime (note: the published release was the next commit). Also, the current `Publish` action runs `cargo publish` in a build matrix which probably isn't the best idea.
