### ISSUE TITLE
GPIO49 and 50 is missing on s3

### ISSUE THREAD

**Issue by farbodpm** [esp-rs/esp-idf-hal#127]
Hello , 
I was going to work with Uart on gpio 49 and 50 but I realized that these pin doesn't defined as pin. What is the reason ?

**Comment by MabezDev** [comment]
Probably a bug, would you mind filing a PR adding those pins?

**Comment by ivmarkov** [comment]
I don't think pins 49 and 50 exist on esp32s3. [Or at least this is what the ESP IDF documentation says](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/gpio.html). Feel free to reopen if the documentation is wrong and you know what their characteristics are.

**Comment by farbodpm** [comment]
Yes you're right. that was my mistake and every pinout has been added to library correctly.
