### ISSUE TITLE
I want to understand how writing a HAL works

### ISSUE THREAD

**Issue by Santiago-Torres14** [esp-rs/esp-idf-hal#129]
Hey there, I don't know if I should be asking this on here, but I didn't find any other place. I want to know where should I start to understand how you guys build this project from the ground up, I'm very novice with this kinda stuff, though I'd love to learn.

**Comment by MabezDev** [comment]
Hey! Thanks for your interest! I have a few resources to take a look at:

- [The esp-rs book](https://esp-rs.github.io/book/) - an overview of our esp specific Rust stuff, with some useful info
- [The Rust embedded book](https://docs.rust-embedded.org/book/) - _The book_ on Rust embedded, the book doesn't use an esp, but it teaches the principles of embedded Rust.
- [esp-rs matrix chatroom](https://matrix.to/#/#esp-rs:matrix.org) - drop in here for any esp rust related questions :)

Hope that helps! Hope to see you around :)
