### ISSUE TITLE
PinDriver on ESP32-C3

### ISSUE THREAD

**Issue by cwoolum** [esp-rs/esp-idf-hal#141]
I'm trying to use `PinDriver` to manager GPIO access on my ESP32-C3 but it looks like it's specifically not available for the chipset. Is this because it has not been implemented yet or because it's just not available at all?

**Comment by mfiumara** [comment]
Maybe the sample is outdated? I'm having the same issue.

**Comment by mfiumara** [comment]
Hey I had the same problem: You are probably looking at the examples on master which is tagged `0.39`, but this seems not the be released yet.

If you take a look at the examples for 0.38.1 you'll see you need to use a different API: https://github.com/esp-rs/esp-idf-hal/blob/v0.38.1/examples/button.rs
