### ISSUE TITLE
Examples iterating PinDriver

### ISSUE THREAD

**Issue by ishigoemon** [esp-rs/esp-idf-hal#145]
With the conversion to PinDriver, examples such as #22 and others utilizing .degrade()/.downgrade() do not seem to be working.

Something like this works, but doesn't seem correct.
```rust
let a = peripherals.pins.gpio1.downgrade_output();
let b = peripherals.pins.gpio2.downgrade_output();
let mut pins = vec![a,b];

for pin in pins.iter_mut() {
    let p = PinDriver::output(pin)?;
    p.set_high()?;
}
```

Apologies if I've missed something obvious, quite new to rust.

**Comment by ivmarkov** [comment]
> Something like this works, but doesn't seem correct.

Why? That's precisely how it is supposed to work?
