### ISSUE TITLE
Add support to call i2c_set_timeout() and i2c_get_timeout() from esp-idf for I2C Master<...>

### ISSUE THREAD

**Issue by ololoshka2871** [esp-rs/esp-idf-hal#149]
I'm using a device that does stretch line SCL of i2c bus. 
I found that in the default configuration, my device is stretching SCL for too long time, so when I'm trying to read from my device. The results is __ESP_ERR_TIMEOUT__.
![image](https://user-images.githubusercontent.com/2912756/195595041-31c3b2ee-4f66-444e-b1b1-596dcc4ade1c.png)

I made a temporary workaround to the problem as follows:
```rust
extern "C" {
    fn i2c_set_timeout(
        i2c_num: esp_idf_sys::i2c_port_t,
        timeout: esp_idf_sys::c_types::c_int,
    ) -> esp_idf_sys::esp_err_t;
    fn i2c_get_timeout(
        i2c_num: esp_idf_sys::i2c_port_t,
        timeout: *mut esp_idf_sys::c_types::c_int,
    ) -> esp_idf_sys::esp_err_t;
}

let config = <i2c::config::MasterConfig as Default>::default()
    .baudrate(100.kHz().into());
let mut i2c = i2c::Master::new(
    dp.i2c0,
    i2c::MasterPins {
        sda: dp.pins.gpio26,
        scl: dp.pins.gpio25,
    },
    config,
).expect("Failed to init i2c");

unsafe { 
    let mut ct: esp_idf_sys::c_types::c_int  = 0;
    i2c_get_timeout(0, &mut ct);
    println!("Current i2c stretching timout: {}", ct);
    i2c_set_timeout(0, 32000);  // <- 32000 is ok for me
}
```
Result:
![image](https://user-images.githubusercontent.com/2912756/195595801-8dd9a198-74d7-4660-b16f-818e68424fdf.png)

**Comment by ivmarkov** [comment]
I think this is addressed already in `master`, in that it has pub methods on `I2cMasterDriver` that allow you to read/write with a timeout.
