### ISSUE TITLE
serial some error handling error

### ISSUE THREAD

**Issue by farbodpm** [esp-rs/esp-idf-hal#156]
In bserial code in "write_bytes" function what happen if the function return none zero len. For example imagine that we are going to send 100 bytes but only 20 bytes sended . What would block error return help ?

**Comment by ivmarkov** [comment]
If you mean `UartTxDriver::write`, it will NOT return an error if less than the number of bytes were written. And you need to repeat writing with the remaining values in your buffer, until everything is written.

Hope that answers your question, as I'm a bit confused as to what exactly is the issue you are trying to address.
