### ISSUE TITLE
SPI device driver is not Send anymore?

### ISSUE THREAD

**Issue by mbuesch** [esp-rs/esp-idf-hal#159]
Since the recent hal SPI rewrite I'm not able to `Send` my SPI based LCD driver anymore. My LCD driver is a struct protected by Mutex. It embeds the SPI driver object.

But `SpiDeviceDriver` and `SpiSharedDeviceDriver` don't implement `Send`.
This used to work fine before, with the old `SpiMasterDriver` before the rewrite.

`SpiSoftCsDeviceDriver` does implement `Send`, but I don't need a CS. (The LCD driver handles this internally due to hardware requirements).
I'm also completely confused by the new interface for when and where to use which struct. A bit of example code would be much appreciated.

Thanks a lot for your help :)

**Comment by ivmarkov** [comment]
> I'm also completely confused by the new interface for when and where to use which struct. A bit of example code would be much appreciated

As in, the two SPI examples in the `examples`  folder are not clear enough?
If you just want to take it easy, simply use `SpiDeviceDriver::new_single`. It is an almost 1:1 replacement of the old `SpiMasterDriver::new`, except that you need to pass the `Dma` param (`Dma::Disabled` usually) outside of the config.

**Comment by mbuesch** [comment]
> As in, the two SPI examples in the examples folder are not clear enough?

Ok. I didn't look into the examples folder.
I would have expected a basic example in the documentation.
I will take a look at the examples folder.

> It is an almost 1:1 replacement of the old SpiMasterDriver::new, except that you need to pass the Dma param (Dma::Disabled usually) outside of the config.

Ok. But is it `Send`?

**Comment by mbuesch** [comment]
What the hell? Why are you closing this?

**Comment by mbuesch** [comment]
Ok, you seem to *just* have *made* it `Send`.
After cargo updating to the latest master commit, my code now compiles again.

Thanks for your help.
