### ISSUE TITLE
Expose possibility to make timers automatically recurring (enable auto reload)

### ISSUE THREAD

**Issue by faern** [esp-rs/esp-idf-hal#187]
In the current version of `esp-idf-hal` (`0.40`) I don't see any way to [enable timer auto reload functionality](https://docs.espressif.com/projects/esp-idf/en/v4.4.3/esp32/api-reference/peripherals/timer.html#_CPPv421timer_set_auto_reload13timer_group_t11timer_idx_t18timer_autoreload_t). The `TimerDriver::new` constructor hardcodes the value for it as `auto_reload: timer_autoreload_t_TIMER_AUTORELOAD_DIS` and provides no means to change it.

I enabled it myself using `esp-idf-sys` directly right after creating the timer like this:
```rust
let mut timer = TimerDriver::new(peripherals.timer00, &timer_config)?;
unsafe { timer_set_auto_reload(timer.group(), timer.index(), timer_autoreload_t_TIMER_AUTORELOAD_EN) };
```
But it feels like something that should be possible to do from this safe abstraction layer? Or is there a reason it's not exposed? What's the recommended way to fire an interrupt at a fixed time interval indefinitely?

**Comment by ivmarkov** [comment]
Sure. If you contribute a PR that puts an `autoreload` settung un `Config`, I'll merge.
