### ISSUE TITLE
SpiDeviceDriver does not implement spi::FullDuplex

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [esp-rs/esp-idf-hal#198]
For example, this is required for [embedded_sdmmc](https://docs.rs/embedded-sdmmc/latest/embedded_sdmmc/index.html) lib

**Comment by dberlin** [comment]
Looks like a duplicate of #3 ?

**Comment by dberlin** [comment]
The latest version of embedded_sdmmc does not require fullduplex, fwiw

**Comment by Vollbrecht** [comment]
closing for #3
