### ISSUE TITLE
data loss on 115200 baudrate 

### ISSUE THREAD

**Issue by farbodpm** [esp-rs/esp-idf-hal#204]
I was checking my uart code. I realized that I have data loss over my serial port, I decided to impl uart read using Interrupt. As I am going to make my changes as a PR. Any advices or tips or help ?

**Comment by MabezDev** [comment]
Here is some prior art that didn't get merged: https://github.com/esp-rs/esp-idf-hal/pull/84. I would also take a look at the discussion, you might not need interrupts to avoid data loss.

**Comment by ivmarkov** [comment]
Because you can use the much simple blocking read that the UART driver is supporting in the meantime. Blocking read is buffered, so it should work quite OK at high speeds.
