### ISSUE TITLE
Matter/Thread support?

### ISSUE THREAD

**Issue by ewrogers** [esp-rs/esp-idf-hal#212]
I am looking to build a few simple IoT accessories using the Matter framework and trying to figure out what support (if any) exists for this in Rust for the ESP32-C3. I know the standard C-based IDF supports this but can't find anything related to in the Rust repositories.

Given how new Matter + ESP32 Rust is, I'm going to assume it is not supported yet. I'd be willing to take a stab at writing some basic stuff using [`esp-idf-svc`](https://github.com/esp-rs/esp-idf-svc), [`esp-wifi`](https://github.com/esp-rs/esp-wifi), or other crates.

I am just not really sure where to even begin with this, as I can't seem to find information at a "low level" of how Matter works and what needs to even be implemented. I can get basic WiFi HTTP server/client working on the ESP32-C3 but not sure how to begin even making it discoverable, implement clusters, etc.

Essentially, I want to create the Rust version of one of these examples:

- [Light Switch ESP32](https://github.com/project-chip/connectedhomeip/tree/master/examples/light-switch-app/esp32)
- [Lighting ESP32](https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/esp32)

Any information on the roadmap of this, and how it can be implemented at a service level, would be helpful.

**Comment by ivmarkov** [comment]
This is the project that should soon support the ESP platform w.r.t. Matter (in pure Rust): https://github.com/project-chip/matter-rs
