### ISSUE TITLE
Missing documentation on features

### ISSUE THREAD

**Issue by VorpalBlade** [esp-rs/esp-idf-hal#242]
The Cargo.toml features of this crate appear to be undocumented. For example:
* What is the difference between alloc in this crate, in esp-idf-svc and alloc_handler in esp-idf-sys?
* There appear to be embassy related features, is that a work in progress or ready?
* The critical-section feature, when do I need it?

I'm new to embedded Rust, and I'm finding the three idf crates (hal, sys and svc) quite confusing. Some brief overview documentation would go a long way.

**Comment by ivmarkov** [comment]
Closing in favor of #258
