### ISSUE TITLE
Add ext0 WakeupReason

### ISSUE THREAD

**Issue by boustrophedon** [esp-rs/esp-idf-hal#256]
In `impl From<esp_sleep_source_t> for WakeupReason`, could we add `esp_sleep_source_t_ESP_SLEEP_WAKEUP_EXT0 => Self::Button,` in addition to the current one for ext1?

ext0 is basically just the single-pin version of ext1. https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#external-wakeup-ext0

It might also be useful to split it out into Ext0 and Ext1(pin) by using https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#_CPPv432esp_sleep_get_ext1_wakeup_statusv

If it would be easier, I can make a PR for either the Ext0 -> Button change alone or splitting them out, whichever is preferred.

**Comment by ivmarkov** [comment]
Let's have for now the simpler solution, where ext0 is mapped to `Button`. PR would be appreciated!
