### ISSUE TITLE
Tracking - Upgrade to embedded-hal alpha.11

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/esp-idf-hal#278]
- [x] spi: add Operation::DelayUs(u32).
- [x]  remove read-only and write-only traits.

implemented with #295

**Comment by andresv** [comment]
`embedded-hal` has reached RC status: https://github.com/esp-rs/esp-idf-hal/pull/295

**Comment by Dominaezzz** [comment]
Guess this can be closed now?

**Comment by Vollbrecht** [comment]
implemented with https://github.com/esp-rs/esp-idf-hal/pull/295
