### ISSUE TITLE
Include simple examples demonstrating the use of various peripherals

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/esp-idf-hal#29]
Like most other HAL crates do, we should include some basic examples demonstrating how to use the various peripherals. This was discussed briefly in our community meeting today, and there seemed to be a consensus that this would be a valuable addition to the repository.

**Comment by andresv** [comment]
I have added examples to documentation for the drivers that I have improved:
* [can](https://github.com/esp-rs/esp-idf-hal/blob/embedded-hal-1-compat/src/can.rs#L5-L33)
* [serial](https://github.com/esp-rs/esp-idf-hal/blob/embedded-hal-1-compat/src/serial.rs#L8-L35)

**Comment by bjoernQ** [comment]
#46 addresses this partly - still more examples needed

**Comment by silent-rain** [comment]
Looking forward to a series of tutorial examples to help beginners quickly master these skills.It's too difficult for beginners to explore alone. 

Do we have a more complete series of examples as of now?  

For example, timer interrupt, RTC, external clock, watchdog, power control, BKP, PWM, read/write FLASH, etc

**Comment by Vollbrecht** [comment]
we have a example dir now in both esp-idf-hal/svc so for the time i will close this. More examples always appreciated!
