### ISSUE TITLE
Why are both arguments to the can interface outputs?

### ISSUE THREAD

**Issue by pcvonz** [esp-rs/esp-idf-hal#293]
I'm working with a dev board that uses GPIO34 (which is input only) for the RX pin of the CAN interface. 
This line:
https://github.com/esp-rs/esp-idf-hal/blob/cfe5086854548be478926567f95ef5192a038685/src/can.rs#L377
forces the use of a GPIO pin that implements the Output trait. Is this intended?

I'm developing on an ESP32. [This board specifically](https://docs.hatlabs.fi/sh-esp32/)

**Comment by ivmarkov** [comment]
I just fixed this in mainline yesterday. This is a bug, but not a showstopper. For `rx` just pass a pin which implements **both** `InputPin` and `OutputPin` and it would work.
