### ISSUE TITLE
Merge `embedded-hal-1-compat` into mainline

### ISSUE THREAD

**Issue by ivmarkov** [esp-rs/esp-idf-hal#30]
This would bring:
* CAN driver support
* Forward compatibility with embedded-hal-1.0-alpha6, while preserving compatibility with embeded-hal V0.2
* Simplified (and hopefully a bit faster) SPI driver, with more `embedded-hal` traits implemented
* Simplified gpio in terms of code size and repetition

@andresv Can you confirm that the CAN driver you contributed works as it is supposed to work in that branch?
Also if you can look into [this comment](https://github.com/esp-rs/esp-idf-hal/pull/27#discussion_r779421312)? I've "fixed" it in the branch, but the thing is, is it indeed a bug that needs fixing?

**Comment by andresv** [comment]
Added fixes for CAN: https://github.com/esp-rs/esp-idf-hal/pull/31

**Comment by andresv** [comment]
It seems `gpio` does not build with `ulp`: https://github.com/esp-rs/esp-idf-hal/runs/4747633442?check_suite_focus=true

**Comment by ivmarkov** [comment]
Fixed, as well as another issue in the (modernized) SPI driver, as well as a bunch of Clippy warnings in the ULP code: https://github.com/esp-rs/esp-idf-hal/commit/2d0554d9878391521cf56a03607e3b6a7158f4b4
