### ISSUE TITLE
Propose: Set esp-idf version 4.3 as deprecated on next release.

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/esp-idf-hal#301]
Since we not actively testing against it, i would advice that we set it's use to deprecated in the next major release and remove it in two major releases. 

Currently we have [this places](https://github.com/search?q=repo%3Aesp-rs/esp-idf-hal%20esp_idf_version%20%3D%20%224.3%22&type=code) where we have conditional configuration for v4.3

**Comment by ivmarkov** [comment]
@Vollbrecht - how to mark it as deprecated?

**Comment by Vollbrecht** [comment]
If that method is Ok for you i also make a PR for esp-idf-svc

**Comment by ivmarkov** [comment]
Merged. Yes, if you can do the same for `esp-idf-svc` that would be great!
