### ISSUE TITLE
Could not find sys in esp_idf_hal

### ISSUE THREAD

**Issue by Zacchaeus-Oluwole** [esp-rs/esp-idf-hal#316]
While i was working on this example https://github.com/esp-rs/esp-idf-hal/blob/master/examples/timer_notify.rs, i got an error message that says could not find sys in esp_idf_hal

**Comment by ivmarkov** [comment]
Yeah, because you are using the released version of the crates, and the example is from the `master` version which has drifted way too much from the released versions.

**Comment by Zacchaeus-Oluwole** [comment]
Thank you ❤️
