### ISSUE TITLE
GPIO22 and GPIO23 missing for ESP32C6

### ISSUE THREAD

**Issue by sjames** [esp-rs/esp-idf-hal#317]
I\m trying to use the ESP32C6 for a project. I want to USE GPIO22 and GPIO23.  I could not find any restrictions in the datasheet that imply that these should not be used.

These GPIOs are not created for the ESP32C6
https://github.com/esp-rs/esp-idf-hal/blob/2d5e382c47e53dbea367de19713325a33c3c4348/src/gpio.rs#L2459

I wonder if this is intentional.

**Comment by ivmarkov** [comment]
No, it is just a typing mistake, sorry.

**Comment by ivmarkov** [comment]
Fixed.
