### ISSUE TITLE
example i2c_master_slave.rs uses GPIO22 which doesn't exist on esp32s3

### ISSUE THREAD

**Issue by maayanhaimdulberg** [esp-rs/esp-idf-hal#329]
Hi all

The example *i2c_master_slave.rs* uses GPIO22 for I2C
![image](https://github.com/esp-rs/esp-idf-hal/assets/147316918/bd76da8d-bc4e-4330-b2a5-e25c289c5f7c)

The thing is, the famous ESP-32-S3-DevKitC-1 and esp32s3 in general, do not have a GPIO22. 
Maybe it is best to change the pins in the example, to suit any kind of esp32?

[esp32s3](https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf#i2c) page 460
![image](https://github.com/esp-rs/esp-idf-hal/assets/147316918/3f71073c-3e2a-4e59-ad7e-10e07f3c4b65)

[esp32](https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf) page 48
![image](https://github.com/esp-rs/esp-idf-hal/assets/147316918/6b984c47-f79c-49e1-8142-23f4d81aae20)

**Comment by ivmarkov** [comment]
PRs welcome!

**Comment by mdolberg** [comment]
Challenge accepted. Hope I did it right. First PR in an open source project ever.
https://github.com/esp-rs/esp-idf-hal/pull/330
