### ISSUE TITLE
Not checking for ESP_FAIL in AsyncCanDriver::transmit

### ISSUE THREAD

**Issue by leonardodanelutti** [esp-rs/esp-idf-hal#350]
For non-blocking implementations of the `embedded-hal` the `ESP_FAIL` error is treated as `WouldBlock`, shouldn't the same be done for the async function implementation?
```rust
pub async fn transmit(&self, frame: &Frame) -> Result<(), EspError> {
    loop {
        let res = self.driver.borrow().transmit(frame, delay::NON_BLOCK);

        match res {
            Ok(()) => return Ok(()),
            Err(e) if e.code() != ESP_ERR_TIMEOUT => return Err(e),
            _ => (),
        }

        WRITE_NOTIFICATION.wait().await;
    }
}
```

**Comment by ivmarkov** [comment]
No idea without digging (again) into the ESP IDF C source code of the TWAI driver...

**Comment by ivmarkov** [comment]
@leonardodanelutti [The way I read the code](https://github.com/espressif/esp-idf/blob/release/v5.1/components/driver/twai/twai.c#L638) (I might be wrong) is that `ESP_FAIL` would only be returned if you are creating the driver without a TX queue (i.e. `tx_queue_len` == 0)

Can you confirm if you are doing that?

**Comment by leonardodanelutti** [comment]
@ivmarkov I actually didn't get that error, I was looking at the async implementation for the CanDriver and it seemed strange that the ESP_FAIL error wasn't also checked. Yes, I think you are right, as it is also written in the documentation, ESP_FAIL is returned only if the TX queue is disabled and another message is transmitting at that moment. When that error occurs, I don't think the function should return, right?

**Comment by ivmarkov** [comment]
Yes I'll patch the driver shortly.

**Comment by ivmarkov** [comment]
https://github.com/esp-rs/esp-idf-hal/commit/f958b77bf094f1dc42ea12ebacc651ed1a244221
