### ISSUE TITLE
Lack of documentation for TimerDriver methods

### ISSUE THREAD

**Issue by KronsyC** [esp-rs/esp-idf-hal#357]
The `esp_idf_hal::timer::TimerDriver` methods are mostly undocumented, which means that users have to go into its source code to investigate the low-level APIs that it calls, in order to actually use it.

**Comment by KronsyC** [comment]
I can take on the task of documenting it if you'd like, but Im not too familiar with the underlying APIs so my documentation may be inaccurate

**Comment by Vollbrecht** [comment]
If you feel like writing some docu please feel free to do so. PR's are welcome.
