### ISSUE TITLE
Conflict between esp-idf-hal and display-interface-spi on embedded-hal version

### ISSUE THREAD

**Issue by mart-e** [esp-rs/esp-idf-hal#369]
Hello,

I have a version conflict when trying to add [`display-interface-spi`](https://crates.io/crates/display-interface-spi) alongside [`esp-idf-hal`](https://crates.io/crates/esp-idf-hal) from crates.io, the first one depends on `embedded-hal = "1.0.0"` while esp-idf-hal is at `1.0.0-rc.1`.
I see this was changed at 27cd1940970aa8b43ff467b2f4f03afb04b52f0f but crates.io is still referring the previous version.

Is it possible to update to solve this conflict?

Thanks

**Comment by MabezDev** [comment]
Use the git version of this crate until a new release has been cut :). See the [patch docs](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section).
