### ISSUE TITLE
Transport(Failed to load system certs: No valid certificate found) (xtensa-esp32s3-espidf/STD)

### ISSUE THREAD

**Issue by blue-freedom-technologies** [esp-rs/esp-idf-hal#393]
There is any way to install a self-signed certificate in a esp32-s3 board using only rust?

**Comment by blue-freedom-technologies** [comment]
Not a problem. Is already closed...

Cheers

**Comment by Vollbrecht** [comment]
If you have a valid error, please report it and all the context. If you have question how to use something the best place is the Matrix Channel.
