### ISSUE TITLE
I2C default  baudrate too high, is 1M, using this parameter is likely to be wrong

### ISSUE THREAD

**Issue by xiaguangbo** [esp-rs/esp-idf-hal#396]
400K is ok

![截图 2024-03-20 18-34-20](https://github.com/esp-rs/esp-idf-hal/assets/102402151/52d7afc8-9ed5-420c-91c8-a13bdacc7d74)

**Comment by teamplayer3** [comment]
could be changed in the course of #397

**Comment by xiaguangbo** [comment]
It's not a big deal
