### ISSUE TITLE
[Discussed] SPI DMA，can it be used now?

### ISSUE THREAD

**Issue by xiaguangbo** [esp-rs/esp-idf-hal#418]
Slint GUI works on esp32c2, esp32c2 happens to have an SPI DMA, if DMA can be used then the refresh speed of the screen will be greatly increased!

**Comment by ivmarkov** [comment]
Most chips have DMA. The DMA is usable with the SPI driver since a very long time. Join the Matrix room and ask your question there, as in terms of what you are trying to achieve.
