### ISSUE TITLE
When `feature = "std"` is enabled, implement std::io::Read and/or std::io::Write for all drivers where this makes sense

### ISSUE THREAD

**Issue by ivmarkov** [esp-rs/esp-idf-hal#430]
Example: Uart. There, we do implement `embedded_hal_async::Read+Write` for the async version of the driver, but we need to do the same for the sync version.

Same can possibly be done for other drivers. For example, writing to `i2s`.

For one, this would allow folks to use `BufReader` from STD to read line-by-line e.g. from Uart (at the cost of extra allocations).

**Comment by okhsunrog** [comment]
I think you can use embedded-io-adapters crate for "converting" from an embedded_io::Read to a std::io::Read or vice versa. uart driver in esp-idf-hal implements both embedded_io and embedded_io_async.
