### ISSUE TITLE
Add an option to set SPI clock pin to None

### ISSUE THREAD

**Issue by okhsunrog** [esp-rs/esp-idf-hal#439]
It can be useful to use only MOSI pin, for example when driving ws2812 led strip using SPI peripheral. esp-idf allows setting pin num to -1 when unused. I can create pull request for this if needed

**Comment by okhsunrog** [comment]
Added PR which resolves this: https://github.com/esp-rs/esp-idf-hal/pull/440

**Comment by Vollbrecht** [comment]
#440 merged
