### ISSUE TITLE
ledc_simple GPIO1 conflicts with UART 0 TX on ESP32

### ISSUE THREAD

**Issue by georgik** [esp-rs/esp-idf-hal#45]
The example contains `peripherals.pins.gpio1` https://github.com/esp-rs/esp-idf-hal/blob/master/examples/ledc-simple.rs#L17

This causes conflict with `--monitor` on ESP32 and the user can see only question marks filling the terminal.

GPIO1 for ESP32 is UART 0 TX, consider changing it to GPIO4.

**Comment by ivmarkov** [comment]
Should be fixed now.
