### ISSUE TITLE
Use SPI Bus for multiple Devices

### ISSUE THREAD

**Issue by agmes4** [esp-rs/esp-idf-hal#466]
I wanna use the Spi Bus for multiple Spi Devices Problem here is that the config for one device is a bit different.
(It is taking data on raising Edge the other on falling.)

So is there any way to change config on runtime of a SpiDeviceDriver or to create two different one so I can pass one to each devices?

**Comment by Vollbrecht** [comment]
Why not just create two or more SpiDeviceDriver instance each with its own config that represents each MODE option?

**Comment by agmes4** [comment]
Tried that already but the driver con just be passed once cause then it get moved and after that I can not create a new one

**Comment by Vollbrecht** [comment]
A SpiDeviceDriver takes a Borrow<SpiDriver>. If you are not familiar with Borrow you can read about [here](https://doc.rust-lang.org/std/borrow/trait.Borrow.html). It allows you to not only pass by `&SpiDriver` but also everything that implements Borrow like an 'Arc<SpiDriver>` etc.

**Comment by agmes4** [comment]
ah thanks refactoring solved it for me the async task messed things a bit up
