### ISSUE TITLE
ADC uses the wrong channel with `embedded_hal > 0.2`

### ISSUE THREAD

**Issue by tecywiz121** [esp-rs/esp-idf-hal#57]
At least I'm pretty sure that's the problem. It seems like the implementation of `OneShot::read` for `embedded_hal == 0.2.7` chooses channel 6 for `Gpio14`, but chooses channel 2 with `embedded_hal == 1.0.0-alpha.7`.

Here's an [example repository](https://github.com/tecywiz121/esp32-adc/blob/cc5bfe05c8646b5c88789397a31740a589e0dfde/src/main.rs#L15) that shows the difference.

The output from the example:

```
Channel 0.2.7: 6
Value   0.2.7: 2179
Channel 1.0.0: 2
Value   1.0.0: 128
```

**Comment by ivmarkov** [comment]
Should be fixed now.
