### ISSUE TITLE
Feature request: VariableLengthSignal::with_capacity( ) -> Self

### ISSUE THREAD

**Issue by Threadzless** [esp-rs/esp-idf-hal#89]
Okay, so `esp_idf_hal::rmt::VariableLengthSignal` uses a `Vec` to store pulses, but doesn't allow the programmer to specify a capacity when it is initialized, which means the underlying array will have to be reallocated multiple times. 

I'd like there to be an alternative function which lets you pick the Vec's capacity when the struct is initialized

**Comment by ivmarkov** [comment]
Would you be willing to contribute a PR for that?

**Comment by Threadzless** [comment]
sure, i'll have it up this evening
